/*
 * Exports
 */
export const appConstants = {
  // Stages
  STAGE_DEV: "dev",
  STAGE_PROD: "prod",

  // AWS
  DEFAULT_REGION: "us-east-1",

  // Cookie
  COOKIE_TIMEOUT_MILLIS: 60 * 60 * 1000, // 1 hour
  COOKIE_TIMEOUT_MILLIS_YEAR: 365 * 24 * 60 * 60 * 1000, // 1 hour
  COOKIE_HTTP_ONLY: true,
  COOKIE_SAME_SITE: "lax" as "lax",

  // Http status codes
  HTTP_STATUS_CODE_SUCCESS: 200,
  HTTP_STATUS_CODE_REDIRECT: 302,
  HTTP_STATUS_CODE_BAD_REQUEST: 400,
  HTTP_STATUS_CODE_FORBIDDEN: 403,
  HTTP_STATUS_CODE_INTERNAL_SERVER_ERROR: 500,

  // Http errors
  HTTP_ERROR_MSG_ACCESS_RESTRICTED: "Access redistricted",
  HTTP_ERROR_MSG_FORBIDDEN_ACCESS: "Forbidden access",
  HTTP_ERROR_MSG_BAD_REQUEST_PARAMS: "Bad request parameters",
  HTTP_ERROR_MSG_INVALID_REQUEST_PARAMS: "Invalid request parameters",
  HTTP_ERROR_MSG_INTERNAL_SERVER_ERROR: "Something went wrong",
  HTTP_ERROR_MSG_GENERIC_ERROR: "Something went wrong. Please try again",

  // Code
  CODE_INVALID_TOKEN: "INVALID_TOKEN",
  CODE_INVALID_DATA: "INVALID_DATA",
  CODE_UNPURE_REQUEST_PARAMS: "UNPURE_REQUEST_PARAMS",
  CODE_SERVER_ERROR: "SERVER_ERROR",
  CODE_UN_AUTHORIZED_ACTION: "UN_AUTHORIZED_ACTION",
  CODE_ONLINE_ORDERING_UNAVAILABLE: "ONLINE_ORDERING_UNAVAILABLE",

  // Admin
  ADMIN_CONTACT_EMAIL_ADDRESS: "shukybadeer@gmail.com",
  COMPANY_LOGO_URL: "https://public.primefaya.com/company_logo.png",
  COMPANY_LOGO_COMPACT_URL:
    "https://public.primefaya.com/company_logo_compact.png",
  COMPANY_LOGO_WIDTH: 200,
  COMPANY_LOGO_HEIGHT: 55,

  // Paypal
  PAYPAL_PAYMENT_LINK_CA: "https://www.paypal.com/ncp/payment/HNZKGJRCCFA88",
  PAYPAL_PAYMENT_LINK_US: "https://www.paypal.com/ncp/payment/P8TFGRSNR574Q ",

  // Business Locale
  BUSINESS_LOCALE_CA: "CA",
  BUSINESS_LOCALE_US: "US",

  // Cognito
  COGNITO_GRANT_TYPE_CODE: "authorization_code",
  COGNITO_GROUP_ADMINS: "Admins",

  // S3
  S3_STORAGE_BUCKET_PREFIX: "ceseelia-storage-",
  SECRET_STORAGE_BUCKET: "secrets.primefaya.com",
  PUBLIC_STORAGE_BUCKET: "public.primefaya.com",

  // DynamoDB
  DYNAMO_TABLE_PREFIX: "ceseelia_",
  DYNAMO_TABLE_PRIME_DINE_PREFIX: "primedine_",

  // DynamoDB Entities
  DYNAMO_ENTITY_SESSION: "SESSION",
  DYNAMO_ENTITY_APP: "APP",
  DYNAMO_ENTITY_USER: "USER",
  DYNAMO_ENTITY_INFO: "INFO",
  DYNAMO_ENTITY_DATA: "DATA",
  DYNAMO_ENTITY_PROFILE: "PROFILE",
  DYNAMO_ENTITY_REWARDS: "REWARDS",
  DYNAMO_ENTITY_COGNITO_DATA: "COGNITO_DATA",
  DYNAMO_ENTITY_COUNTS: "COUNTS",
  DYNAMO_ENTITY_RECORD: "RECORD",
  DYNAMO_ENTITY_FEATURE_REQUEST: "FEATURE_REQUEST",
  DYNAMO_ENTITY_CONTACT_US_REQUEST: "CONTACT_US",
  DYNAMO_ENTITY_FEEDBACK: "FEEDBACK",
  DYNAMO_ENTITY_LAUNCH_SUBSCRIPTION: "LAUNCH_SUBSCRIPTION",
  DYNAMO_ENTITY_NOTIFICATION_SETTINGS: "NOTIFICATION_SETTINGS",
  DYNAMO_ENTITY_PURCHASE: "PURCHASE",
  DYNAMO_ENTITY_SUBSCRIPTION: "SUBSCRIPTION",
  DYNAMO_ENTITY_REQUEST_SENT: "REQUEST_SENT",
  DYNAMO_ENTITY_APPROVED: "APPROVED",
  DYNAMO_ENTITY_DENIED: "DENIED",
  DYNAMO_ENTITY_MEMBER: "MEMBER",
  DYNAMO_ENTITY_STORE: "STORE",
  DYNAMO_ENTITY_APP_STORE: "APP_STORE",
  DYNAMO_ENTITY_OVERVIEW: "OVERVIEW",
  DYNAMO_ENTITY_SETTINGS: "SETTINGS",

  // DynamoDB Index
  INDEX_NAME_COGNITO_IDENTIFIER_GSI: "CognitoIdentifierGSI",
  INDEX_NAME_USER_EMAIL_GSI: "UserEmailGSI",

  // S3
  S3_BUCKET_PRIMEFAYA_PRIVATE_STORAGE: "secrets.primefaya.com",
  S3_BUCKET_PRIMEFAYA_GCP_FCM_PKEY: "gcp/fcm_pkey.json",
  S3_UPLOAD_URL_EXPIRY_SECONDS: 3600, // 1 hour
  S3_DOWNLOAD_URL_EXPIRY_SECONDS: 1800, // # 30 minutes
  S3_FOLDER_USER_ASSETS: "user-assets",
  S3_FOLDER_ONLINE_ORDERING_INVOICES: "woo-invoice",
  S3_FILE_AVATAR: "avatar",
  S3_SUFFIX_AVATAR_IMG: "avatarImg", // avatar image
  S3_ASSET_TYPE_PNG: "png",
  S3_ASSET_TYPE_JPG: "jpg",
  S3_ASSET_TYPE_JPEG: "jpeg",

  // Route53
  ROUTE_53_APP_HOSTED_ZONE: "Z08813271XPXHBGXB108O",
  ROUTE_53_COMPANY_ROOT_DOMAIN: "ceseelia.com",
  ROUTE_53_APP_ROOT_DOMAIN: "merchant.ceseelia.com",
  ROUTE_53_STORAGE_BASE_DOMAIN: "storage.ceseelia.com",
  ROUTE_53_ASSETS_BASE_DOMAIN: "assets.ceseelia.com",

  // Limits
  QUERY_LIMIT: 10,
  LAMBDA_INPUT_STRING_MAX_LENGTH: 100,
  DATA_VERSIONS_LIMIT: 25, // 100,

  // Locales
  LOCALE_EN: "en", // English
  LOCALE_ID: "id", // Bahasa Indonesia

  // User
  USER_PERMISSION_ADMIN: "ADMIN",
  USER_PERMISSION_MODERATOR: "MODERATOR",

  // SES
  SES_DEFAULT_FROM_ADDRESS: "support@ceseelia.com",

  // Currency
  CURRENCY_USD: "USD",
  CURRENCY_CAD: "CAD",

  // Currency Sign
  CURRENCY_SIGN_USD: "$",
  CURRENCY_SIGN_CAD: "$",

  // Errors
  ILLEGAL_USER_AVATAR_URI: "IllegalUserAvatarUri",
  ILLEGAL_IMAGE_TYPE: "IllegalImageType",
  ILLEGAL_IMAGE_TYPE_ERROR: "IllegalImageTypeError",
  S3_OBJECT_NOT_FOUND_ERROR: "ObjectNotFound",
  S3_ILLEGAL_KEY_ATTEMPT: "IllegalS3KeyAttempt",
  S3_ILLEGAL_KEY_COMBINATION: "IllegalS3KeyCombination",
  USER_NOT_FOUND_ERROR: "userNotFoundError",
  USER_DEACTIVATED_ERROR: "userDeactivatedError",
  UPLOAD_IMAGE_LIMIT_EXCEEDED_ERROR: "UploadImageLimitExceeded",
  DYNAMO_DB_PUT_ITEM_ERROR: "ErrorStoringData",
  DYNAMO_DB_QUERY_ERROR: "ErrorQueryingData",
  DYNAMO_DB_UPDATE_ERROR: "ErrorUpdatingData",
  DYNAMO_DB_DELETING_ERROR: "ErrorDeletingData",

  // REGEX
  REGEX_INSTAGRAM_PATTERN:
    "(http|HTTP|https|HTTPS)://(www.instagram.com|WWW.INSTAGRAM.COM|instagram.com|INSTAGRAM.COM)/*",
  REGEX_META_PATTERN:
    "(http|HTTP|https|HTTPS)://(www.facebook.com|WWW.FACEBOOK.COM|facebook.com|FACEBOOK.COM)/*",
  REGEX_YOUTUBE_PATTERN:
    "(http|HTTP|https|HTTPS)://(www.youtube.com|WWW.YOUTUBE.COM|youtube.com|YOUTUBE.COM)/*",
  REGEX_TIKTOK_PATTERN:
    "(http|HTTP|https|HTTPS)://(www.tiktok.com|WWW.TIKTOK.COM|tiktok.com|TIKTOK.COM)/*",
  REGEX_TWITTER_PATTERN:
    "(http|HTTP|https|HTTPS)://(www.twitter.com|WWW.TWITTER.COM|twitter.com|TWITTER.COM)/*",

  // Payment
  PLAN_TYPE_FREE: "PLAN_FREE",
  PLAN_TYPE_GOLD: "PLAN_GOLD",
  PLAN_TYPE_FREE_SERVICE_LIMIT: 1,
  PLAN_TYPE_FREE_STORAGE_LIMIT_B: 104857600, // 100 MB
  PLAN_TYPE_FREE_STORAGE_LIMIT_MB: 100, // 100 MB
  PLAN_TYPE_GOLD_SERVICE_LIMIT: 10,
  PLAN_TYPE_GOLD_STORAGE_LIMIT_B: 5368709120, // 5 GB
  PLAN_TYPE_GOLD_STORAGE_LIMIT_GB: 5, // 5 GB
  RECEIPT_SOURCE_APP_STORE: "app_store",
  RECEIPT_SOURCE_GOOGLE_PLAY: "google_play",

  // TTL
  TTL_MILLIS_2_YEARS: 2 * 365 * 24 * 60 * 60,
  TTL_MILLIS_10_YEARS: 10 * 365 * 24 * 60 * 60,

  // Secrets Manager

  // SQS
  MAX_BATCH_SIZE: 10,
  SQS_MESSAGE_TOPIC_ID_WOO_HANDLE_STRIPE_EVENT: "WOO_HANDLE_STRIPE_EVENT",

  // Vars
  NA: "NA",
  YOU: "You",
  ONE_30_DAYS: 30 * 24 * 60 * 60,
  ONE_YEAR: 365 * 24 * 60 * 60,
  STORAGE_BYTES_MAX_ALLOWED: 100 * 1024,

  // STRIPE
  STRIPE_SK_NOT_EXISTS: "STRIPE_SK_NOT_EXISTS",

  /*
   * Store
   */
  // Financial
  STORE_DEFAULT_SALES_COMMISSION_CENTS: 125,

  // Store themes
  STORE_TEMPLATE_DIGITAL_STORE: "TEMPLATE_DIGITAL_STORE",
  STORE_THEME_DEFAULT: 'THEME_DEFAULT',

  // Store order type
  STORE_ORDER_TYPE_DELIVERY: "DELIVERY",
  STORE_ORDER_TYPE_PICKUP: "PICKUP",

  // Store item custom attribute type
  STORE_ITEM_CUSTOM_ATTRIBUTRE_TYPE_MULTI_SELECT: "MULTI_SELECT",
  STORE_ITEM_CUSTOM_ATTRIBUTRE_TYPE_COUNTER: "COUNTER",

  // Store member permision
  STORE_MEMBER_PERMISSION_ADMIN: "ADMIN",
  STORE_MEMBER_PERMISSION_MERCHANT: "MERCHANT",

  // Store business currency
  STORE_CURRENCY_POSITION_LEFT: "LEFT",
  STORE_CURRENCY_POSITION_RIGHT: "RIGHT",

  // Store rewards redemption
  STORE_REWARDS_REDEMPTION_METHOD_POINTS_TO_MONEY: "POINTS_TO_MONEY",
  STORE_REWARDS_REDEMPTION_METHOD_POINTS_TO_DISCOUNT: "POINTS_TO_DISCOUNT",
};
